repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: detect-private-key
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: text-unicode-replacement-char
