repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-executables-have-shebangs
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: detect-private-key
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        entry: hadolint
