##    Checks the code logic, style and more
# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# Github: https://github.com/btschwertfeger
#
# Workflow to build the test suite and run the unit tests.

name: Unit Tests

on:
  workflow_call:

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.17
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk add --update linux-headers libc-dev g++ build-base git cmake libaec-dev netcdf-dev hdf5-dev curl-dev
          git clone https://github.com/Unidata/netcdf-cxx4.git
          cd netcdf-cxx4
          cmake -S . -B build
          cmake --build build
          cd build
          ctest
          make install
          cd ../..
          rm -rf netcdf-cxx4

      - name: Test BiasAdjustCXX
        run: |
          make dev
          make test
